services:
  app:
    image: <your-account-ID>.dkr.ecr.eu-central-1.amazonaws.com/fady/django_skeleton:1
    env_file: .env
    expose:
      - "8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
